//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IJunior.TypedScenes
{
    using UnityEngine.SceneManagement;
    using IJunior.StateMachine;
    
    public class Game : TypedScene<GameStateMachine>
    {
        
        private const string _sceneName = "Game";
        
        public static void Load(LoadSceneMode loadSceneMode = LoadSceneMode.Single)
        {
            LoadScene(_sceneName, loadSceneMode);
        }
        
        public static UnityEngine.AsyncOperation LoadAsync(LoadSceneMode loadSceneMode = LoadSceneMode.Single)
        {
            return LoadScene(_sceneName, loadSceneMode);
        }

        public static void Load<TState>(LoadSceneMode loadSceneMode = LoadSceneMode.Single) where TState : State<GameStateMachine>
        {
            LoadScene<TState>(_sceneName, loadSceneMode);
        }

        public static void Load<T>(T argument, LoadSceneMode loadSceneMode = LoadSceneMode.Single)
        {
            LoadScene(_sceneName, loadSceneMode, argument);
        }
    }
}
